version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release
      - echo playwright browsers...
      - pwsh bin/Debug/net8.0/playwright.ps1 install
  post_build:
    commands:
      - echo Running tests...
      - dotnet test --configuration Release --no-build --logger "html;LogFileName=TestResults.html"

artifacts:
  files:
    - '**/TestResults/**/*'
  discard-paths: yes